import { makeImageSection } from './contents.js';
export const homeData = [
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=bqyJkx/hzp2fwmJDP/qx8LbXn8n6DHxfK0B4sMkk',
    title: '톱스타, 그 자체',
    status: 'NEW',
    people: '1.6',
    message: '다시 톱스타가 될 수 있을까?',
  },
  {
    firstInfo: '오늘 UP',
    firstSubInfo: '206',
    secondInfo: '오늘 신작',
    secondSubInfo: '10',
    thirdInfo: '오리지널',
    thirdSubInfo: '2,330',
    fourthInfo: '완결까지 정주행',
    fifthInfo: '독립운동가 웹툰',
    sixthInfo: '오늘랭킹',
    sixthSunInfo: '1위',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=gPEB1/hzhOklLHwx/b9atKBc9aVXCF3Gu9KKKHK',
    title: '공모전',
  },
  {
    adtnlInfo: '완결',
  },
  {
    title: '요일연재TOP',
    contents: '더보기👉',
  },
  {
    tagName: 'span',
    contents: '3,495',
    className: 'section_title',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=JKbkM/hzhOksSPjb/Zk4kiHai3IGS77dRy1iO1K&filename=th2',
    rankNum: '1위',
    title: '악당의 아빠를 꼬셔라',
    people: '159.2',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=rOfMN/hyEdeEtJFz/63XlMqYRjhokso828Ki6k0&filename=th2',
    rankNum: '2위',
    title: '나 혼자만 레벨업',
    people: '417.4',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2',
    rankNum: '3위',
    title: '궁귀검신',
    people: '51.2',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=bJfSQM/hzhOey4Ce1/vdfn3bixVAOmkJYJOklf41&filename=th2',
    rankNum: '4위',
    title: '아빠, 나 이결혼 안 할래요!',
    people: '159.2',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=nqcae/hy41PrwQNy/owLlWx5cXQR4NciK7kjcc1&filename=th2',
    rankNum: '5위',
    title: '딸 바보가 되었습니다',
    people: '55.2',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=b7H7Jx/hzmU3lmHWf/PYTUMe8KmuFYbvLETjjfOk&filename=th2',
    star: '★',
    grade: '9.9',
    title: '재앙급 영웅님이 귀환하셨다',
    people: '57.2',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=6WrkN/hzhOi9Q3rx/K9EcOe49J8tPsqkcZY9KB1&filename=th2',
    star: '★',
    grade: '9.8',
    title: '카니발 베이비',
    people: '17',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=c7aN0E/hy41NmZFbx/XpuVPoG811XwKto4vKtxYK&filename=th2',
    star: '★',
    grade: '9.9',
    title: '24분의 1 로멘스',
    people: '63.8',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=S1kxU/hyEdlYjRrz/e1OeuUKOpw07xau22O8N6k&filename=th2',
    star: '★',
    grade: '10.0',
    title: '악녀가 사랑할 때',
    people: '133',
  },
  {
    url: '	https://dn-img-page.kakao.com/download/resource?kid=wIHwB/hzhOmRyx4s/c720DwZNXp99QzWbKrljIK&filename=th2',
    star: '★',
    grade: '9.9',
    title: '대놓고 사내연애',
    people: '35.5',
  },
  {
    title: '기대신작 TOP',
    contents: '더보기👉',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=vEn5x/hzp2ec8RPh/fT0WMvndQ54lxcYZPOQAIk&filename=th2',
    className: 'first_new_thing',
    title: '프로파일러(개정판)',
    people: '4.8',
    message: '동기 없는 범죄는 없다',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=gJnVp/hzhOlZQA6V/bOLsPczkpDmGtHlcutyopk&filename=th2',
    className: 'second_new_thing',
    title: '별이 빈 소원',
    people: '12.6',
    message: '갑자기 이 이상한 초능력은 뭐야?',
  },
  {
    title: '로맨스 TOP',
    contents: '더보기👉',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2',
    title: '누구의 아이를 낳을까',
    grade: '9.7',
    people: '26.5',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2',
    title: '누구의 아이를 낳을까',
    grade: '9.7',
    people: '26.5',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2',
    title: '누구의 아이를 낳을까',
    grade: '9.7',
    people: '26.5',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2',
    title: '누구의 아이를 낳을까',
    grade: '9.7',
    people: '26.5',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2',
    title: '누구의 아이를 낳을까',
    grade: '9.7',
    people: '26.5',
  },
  {
    title: '로판 TOP',
    contents: '더보기👉',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2',
    title: '미연시 게임 속 하찮은 엑스트라',
    grade: '9.8',
    people: '23.7',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2',
    title: '미연시 게임 속 하찮은 엑스트라',
    grade: '9.8',
    people: '23.7',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2',
    title: '미연시 게임 속 하찮은 엑스트라',
    grade: '9.8',
    people: '23.7',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2',
    title: '미연시 게임 속 하찮은 엑스트라',
    grade: '9.8',
    people: '23.7',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2',
    title: '미연시 게임 속 하찮은 엑스트라',
    grade: '9.8',
    people: '23.7',
  },
  {
    title: '일간 랭킹 TOP',
    contents: '더보기👉',
  },
  {
    rankingNum: '1',
    url: 'https://dn-img-page.kakao.com/download/resource?kid=tiNdF/hzp2kKX00t/KlYYVXjccU6Crr6NCxTKvK&filename=th2',
    title: '남편님, 다시 결혼해 주세요!',
    icon: 'New',
    people: '30.9',
    genre: '로판',
    writer: '미우, 파라구',
    date: '금',
  },
  {
    rankingNum: '2',
    url: 'https://dn-img-page.kakao.com/download/resource?kid=tiNdF/hzp2kKX00t/KlYYVXjccU6Crr6NCxTKvK&filename=th2',
    title: '남편님, 다시 결혼해 주세요!',
    icon: '',
    people: '30.9',
    genre: '로판',
    writer: '미우, 파라구',
    date: '금',
  },
  {
    rankingNum: '3',
    url: 'https://dn-img-page.kakao.com/download/resource?kid=tiNdF/hzp2kKX00t/KlYYVXjccU6Crr6NCxTKvK&filename=th2',
    title: '남편님, 다시 결혼해 주세요!',
    icon: 'New',
    people: '30.9',
    genre: '로판',
    writer: '미우, 파라구',
    date: '금',
  },
  {
    title: '추천 이벤트',
    contents: '더보기👉',
  },
  {
    url: 'https://dn-img-page.kakao.com/download/resource?kid=bnJszq/hzp2nnDXAM/raGUe2y54VTgPi6k8JHXoK',
  },
];
