export const WebtoonData = [
    {
      _id: 1,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5만명",
      genre: '4',
      rating: '10.0',
      ageLimit: 'All',
      week: [0],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 2,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5만명",
      genre: '4',
      rating: '10.0',
      ageLimit: 'All',
      week: [1, 2],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 3,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5만명",
      genre: '4',
      rating: '10.0',
      ageLimit: '15',
      week: [3],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 4,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5만명",
      genre: '4',
      rating: '10.0',
      ageLimit: 'All',
      week: [5],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 5,
      title: "이차원 용병",
      img: "http://dn-img-page.kakao.com/download/resource?kid=qklnd/hyCvm4LfZf/xUw9OCkXIPkU5eNV5nuMb0&filename=th2",
      subscriptions: "103만명",
      genre: '5',
      rating: '9.7',
      ageLimit: 'All',
      week: [6],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 6,
      title: "SSS급 죽어야 사는 헌터",
      img: "http://dn-img-page.kakao.com/download/resource?kid=2XcHF/hzacfyyDaP/AQvywUuQOQ9bmwXoyvCKbK&filename=th2",
      subscriptions: "91.9만명",
      genre: '5',
      rating: '9.5',
      ageLimit: 'All',
      week: [7],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 7,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5만명",
      genre: '6',
      rating: '8.8',
      ageLimit: 'All',
      week: [2, 3],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 8,
      title: "1레벨 플레이어",
      img: "http://dn-img-page.kakao.com/download/resource?kid=6iJrN/hzmU1aifCt/9kruzeXja6oBtgyFLycHK1&filename=th2",
      subscriptions: "19.6만명",
      genre: '6',
      rating: '9.1',
      ageLimit: '15',
      week: [4, 5],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 9,
      title: "어딜 봐요 매니저님",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cqZA0V/hzacd84mNX/s3PtIZmocIWK7ABeG0ac31&filename=th2",
      subscriptions: "18.4만명",
      genre: '7',
      rating: '9.2',
      ageLimit: 'All',
      week: [1, 6],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 10,
      title: "경계인",
      img: "http://dn-img-page.kakao.com/download/resource?kid=c3xG5E/hzhOohQOpW/KoaGkWzM6mK9TPOIb2wbE0&filename=th2",
      subscriptions: "9.4만명",
      genre: '7',
      rating: '9.3',
      ageLimit: '15',
      week: [3, 5],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 11,
      title: "백작가의 망나니가 되었다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cbjtkI/hzacgYFTkq/PSAiujZt9kOXMOPj1XT7LK&filename=th2",
      subscriptions: "131만명",
      genre: '7',
      rating: '7.2',
      ageLimit: 'All',
      week: [0, 2],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 12,
      title: "정령왕의 딸",
      img: "http://dn-img-page.kakao.com/download/resource?kid=22qoX/hyCvmRQDSL/5JDKyDHkJgBOI69lg4qdJ1&filename=th2",
      subscriptions: "75만명",
      genre: '8',
      rating: '6.6',
      ageLimit: 'All',
      week: [3, 4],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 13,
      title: "옷소매 붉은 끝동",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bdXfpL/hzb7sQkGfQ/NT4fYxdUKZWbW7v9Sj4D81&filename=th2",
      subscriptions: "58.4만명",
      genre: '8',
      rating: '7.2',
      ageLimit: '15',
      week: [2, 3],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 14,
      title: "미필적 고의에 의한 관계",
      img: "http://dn-img-page.kakao.com/download/resource?kid=b60gs5/hyQ9S2BUwT/Vv2RtbZab85B2G8UKpaxX0&filename=th2",
      subscriptions: "35.2만명",
      genre: '3',
      rating: '8.5',
      ageLimit: 'All',
      week: [4],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 15,
      title: "내일의 으뜸",
      img: "http://dn-img-page.kakao.com/download/resource?kid=coktW/hzb7AOnehU/IcN3VcXjLBdbTpRPv8sqQK&filename=th2",
      subscriptions: "23.4만명",
      genre: '3',
      rating: '7.4',
      ageLimit: 'All',
      week: [3],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 16,
      title: "오라버니가 너무 순해서 걱정이다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=9AhFq/hzb7v7qYBA/VfbltpT4NcWVRRvBSo7ySK&filename=th2",
      subscriptions: "54.1만명",
      genre: '4',
      rating: '8.1',
      ageLimit: 'All',
      week: [7],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 17,
      title: "왜 이러세요, 공작님!",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bpui9e/hyVkMY297U/x6PEfl4IECW7Fi2AkBXL31&filename=th2",
      subscriptions: "131.7만명",
      genre: '5',
      rating: '6.5',
      ageLimit: '15',
      week: [1],
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 18,
      title: "2회차는 레드카펫으로",
      img: "http://dn-img-page.kakao.com/download/resource?kid=jiR4L/hzb7s4AGjp/rSkNu0yVQGFTB3vcnA7Yd1&filename=th2",
      subscriptions: "35.5만명",
      genre: '4',
      rating: '9.1',
      ageLimit: 'All',
      week: [2],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 19,
      title: "흑막을 버리는 데 실패했다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=liDhp/hzp2mPH4pp/avQh3sIi2DG85rCRUegvG0&filename=th2",
      subscriptions: "29.9만명",
      genre: '5',
      rating: '9.6',
      ageLimit: '15',
      week: [3],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 20,
      title: "절대무신",
      img: "http://dn-img-page.kakao.com/download/resource?kid=d7xIJb/hy41GOLe3P/buSZKwUMyLBtvX0KxkWSik&filename=th2",
      subscriptions: "61.1만명",
      genre: '7',
      rating: '10.0',
      ageLimit: 'All',
      week: [5],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 21,
      title: "비뢰도",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cyq0ma/hzb7yDg2ke/bIzebxQnLC3RJj7mkrwcUK&filename=th2",
      subscriptions: "104.1만명",
      genre: '7',
      rating: '9.5',
      ageLimit: 'All',
      week: [3],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 22,
      title: "호위무사",
      img: "http://dn-img-page.kakao.com/download/resource?kid=O2gvI/hy41MPonM0/exDflmPQEKmkXbFHoWjRsk&filename=th2",
      subscriptions: "23.5만명",
      genre: '7',
      rating: '8.4',
      ageLimit: '15',
      week: [4],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 23,
      title: "마검왕",
      img: "http://dn-img-page.kakao.com/download/resource?kid=L1YaG/hyCvfFupwI/RKKFw4IwDhfsppjUQooOY1&filename=th2",
      subscriptions: "229.8만명",
      genre: '6',
      rating: '9.2',
      ageLimit: 'All',
      week: [3],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 24,
      title: "나쁜 색기 [개정판]",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bhEjzw/hzhOfkJ4Le/Qk9yTzliowfFfy7i3lSYfK&filename=th2",
      subscriptions: "6.8만명",
      genre: '8',
      rating: '9.9',
      ageLimit: 'All',
      week: [5],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 25,
      title: "우연한 친구",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bWRnqq/hy41LwsibS/tFl0ThHhYEwCWrTjyk2U2k&filename=th2",
      subscriptions: "8.9만명",
      genre: '4',
      rating: '10.0',
      ageLimit: 'All',
      week: [2],
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
  ];