const homeData = [
  {
    category: "요일 연재 TOP",
    cardStyle: 0,
    divByDay: true,
    data: [
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ci204O/hzp2fXpq0c/kJYIUtWhdIWWczAEIGftD1&filename=th2",
          title: "하필이면 까마귀가 되어버렸다",
          info: "1위",
          user: "33.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dpadT7/hzhOgqBSHA/HpZA6H7vPawsODuGIQaQO0&filename=th2",
          title: "이번 생은 가주가 되겠습니다",
          info: "2위",
          user: "122.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhaZNx/hzhOgKHpz7/xbaDBtEqubGcBNaJ6pdta1&filename=th2",
          title: "남주를 주웠더니 남편이 생겨버렸다",
          info: "3위",
          user: "51.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "4위",
          user: "57.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4zVlh/hzace79wlr/eLd8UzzCyPOnKFc6bh14tk&filename=th2",
          title: "사장님의 특별지시",
          info: "5위",
          user: "41.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhe9o7/hzmU3zpvL3/DWRcsmPxJAlrjDw7MkGWwK&filename=th2",
          title: "8클래스 마법사의 회귀",
          info: "9.9",
          user: "81.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cburiM/hy41PLVqom/1BQa5TQO17iJiSIsRTKVr0&filename=th2",
          title: "나는 이 집 아이",
          info: "9.9",
          user: "212만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bBN4dK/hzhOhvRXM4/ykApb2W8w90ILBWRgWANM0&filename=th2",
          title: "악당과 계약 가족이 되었다",
          info: "10.0",
          user: "49.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=F0xa7/hzb7t2VZrr/HXgP5lNu9sKYsI30QFZKL1&filename=th2",
          title: "아기가 생겼어요",
          info: "10.0",
          user: "29.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bEZGwb/hyQ9UfEEiQ/Hpt0oUWQfjX3lQbt2816wk&filename=th2",
          title: "유리의 성",
          info: "10.0",
          user: "42.9만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bEZGwb/hyQ9UfEEiQ/Hpt0oUWQfjX3lQbt2816wk&filename=th2",
          title: "유리의 성",
          info: "10.0",
          user: "42.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cSoIgy/hy41H00NFE/juIgEt25Th0lkY0C9SMhe1&filename=th2",
          title: "나를 기억하나요",
          info: "9.8",
          user: "55만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=QxTFz/hyEdj6EpG9/ZQ7ZCG53bh79zcSBhdi29k&filename=th2",
          title: "궁 [컬러판]",
          info: "9.9",
          user: "49.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4zVlh/hzace79wlr/eLd8UzzCyPOnKFc6bh14tk&filename=th2",
          title: "사장님의 특별지시",
          info: "9.9",
          user: "41.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bOkrb8/hzp2j6CvOQ/kbjxtdpkNHpQZpmThVLos1&filename=th2",
          title: "사내 맞선",
          info: "10.0",
          user: "198.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=52JL3/hyZ8D4ijJj/5l1NJOM5nAeWLHVkZpVFM0&filename=th2",
          title: "용, 감한 연애",
          info: "9.8",
          user: "30.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=b8XUDY/hzacdHFgq0/6K59Mtk85VEQmCLooyEv71&filename=th2",
          title: "이건 명백한 사기결혼이다",
          info: "9.9",
          user: "124.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=PbSU5/hzhOgKD3Th/kF9pdCDfC6ozdIk3IS8vH1&filename=th2",
          title: "무협지 최고 악당의 귀한 딸입니다",
          info: "9.9",
          user: "76.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhaZNx/hzhOgKHpz7/xbaDBtEqubGcBNaJ6pdta1&filename=th2",
          title: "남주를 주웠더니 남편이 생겨버렸다",
          info: "10.0",
          user: "51.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bQvfe8/hzb7yjh2WP/did3KdCAAbDrS0mgPk4tW0&filename=th2",
          title: "꼬마 영애님은 주연들을 길들인다",
          info: "9.9",
          user: "17.9만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=QJhHJ/hzmU2mS8QL/VGvfIN05JYKpaWllHiYyXk&filename=th2",
          title: "부드러운 폭군",
          info: "9.4",
          user: "25.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=q5nJN/hy41Qj7EdG/q2yxuTYAdPczsD5sihMGR0&filename=th2",
          title: "오늘부터 황녀?!",
          info: "9.8",
          user: "32만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bCelQj/hzhOek5lep/SqHCJcs1qIY52j3sjf93Xk&filename=th2",
          title: "롱리브더킹",
          info: "9.9",
          user: "246.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bzScC1/hy41JR2B5d/K77hP8f4CokREaqf4T8o1K&filename=th2",
          title: "환골탈태",
          info: "10.0",
          user: "116.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "9.9",
          user: "57.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cXUoze/hy41PZ2lMh/DdS2BlmZjHKkMUCEvBHC71&filename=th2",
          title: "다시 한번 아이돌",
          info: "9.9",
          user: "37.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwUHkQ/hzhOeFwHdS/EhHwSjL3h1svCK6RExMO61&filename=th2",
          title: "월요일이 사라졌다",
          info: "9.9",
          user: "11.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dYU8b/hzb7xxhnSp/Da0aUtvYVY3c19FuUz0oK1&filename=th2",
          title: "막장드라마의 제왕",
          info: "9.9",
          user: "28.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=drGb4/hzhOjGWQak/dE94GJ4Cle0loMEKl7nX0K&filename=th2",
          title: "가족이 되는 방법",
          info: "10.0",
          user: "20.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bxWVWL/hzacd8zhM5/BVGMMmESRZyWCsUJ9uWw6K&filename=th2",
          title: "당근 있어요?",
          info: "9.6",
          user: "9.9만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=rZ86p/hy41QqopHa/cYNFyoTZNAty1sh8vmpE81&filename=th2",
          title: "가로지나 세로지나 꽃은 핀다 [BL] [개정판]",
          info: "10.0",
          user: "8.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bk1XSw/hzp2iGucNC/uGzbTqsd7jxujKmaSJ1jY0&filename=th2",
          title: "미로의 행진곡",
          info: "9.4",
          user: "4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=e6voS/hy41M9zDt6/IinBxHk6kIL1BL63KEm5E0&filename=th2",
          title: "그 알파를 꼬시는 법 [BL]",
          info: "10.0",
          user: "20.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bjInsQ/hyORYE18fc/SHV461YOWiyk8bb1avebP1&filename=th2",
          title: "레벨업 못하는 플레이어",
          info: "9.9",
          user: "71.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=r5DAK/hzp2fXklXs/2VBp5RLYmX05uX9SJncIbK&filename=th2",
          title: "더 라이브",
          info: "10.0",
          user: "43.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9Eoo5/hyATyGp2En/pYYjRkJJIrpHEvDible6T0&filename=th2",
          title: "묵향 다크레이디",
          info: "9.9",
          user: "132만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=MQg1v/hzb7BfpnWX/5GoYNrCZVkmw6Zw3txDCak&filename=th2",
          title: "4000년 만에 귀환한 대마도사",
          info: "9.8",
          user: "97.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cl7FU2/hzmU09ROsy/kED2UVJzoYZMpIQG3TWTuK&filename=th2",
          title: "튜토리얼이 너무 어렵다",
          info: "8.6",
          user: "52.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=iki74/hyATquUtXS/yuLaGvsL04VfHfusl7aOMK&filename=th2",
          title: "독고3 [완전판]",
          info: "9.7",
          user: "104.1만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cgjIXG/hyVkI2CXF4/6pOOV3CUzwy61ldC6Uji20&filename=th2",
          title: "화산권마",
          info: "9.6",
          user: "34.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cSNIYU/hy41O64Fhu/EBsV20NgKCOBUZcfb9iICK&filename=th2",
          title: "천마, 리치왕의 무림을 부수다",
          info: "9.7",
          user: "32.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=6dhu9/hzhOey7saj/8xyRTDlCO1vKMnyH4Qeq00&filename=th2",
          title: "스위치",
          info: "9.6",
          user: "12.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bHcP0X/hzhOiO3GzX/TskY2u0bY2elhyZ8spdFd0&filename=th2",
          title: "천하제일 표사",
          info: "9.6",
          user: "16.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bCVX6Q/hyATuqpQ2h/RGNsYqdzi79pTwbKdyGmT0&filename=th2",
          title: "학사재생",
          info: "9.9",
          user: "167.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cr2Kc9/hzb7ycnmms/tm18dfsnOsvzzyORUJaUP1&filename=th2",
          title: "신마",
          info: "9.2",
          user: "8.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ci204O/hzp2fXpq0c/kJYIUtWhdIWWczAEIGftD1&filename=th2",
          title: "하필이면 까마귀가 되어버렸다",
          info: "1위",
          user: "33.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dpadT7/hzhOgqBSHA/HpZA6H7vPawsODuGIQaQO0&filename=th2",
          title: "이번 생은 가주가 되겠습니다",
          info: "2위",
          user: "122.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhaZNx/hzhOgKHpz7/xbaDBtEqubGcBNaJ6pdta1&filename=th2",
          title: "남주를 주웠더니 남편이 생겨버렸다",
          info: "3위",
          user: "51.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "4위",
          user: "57.9만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bEZGwb/hyQ9UfEEiQ/Hpt0oUWQfjX3lQbt2816wk&filename=th2",
          title: "유리의 성",
          info: "10.0",
          user: "42.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cSoIgy/hy41H00NFE/juIgEt25Th0lkY0C9SMhe1&filename=th2",
          title: "나를 기억하나요",
          info: "9.8",
          user: "55만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=QxTFz/hyEdj6EpG9/ZQ7ZCG53bh79zcSBhdi29k&filename=th2",
          title: "궁 [컬러판]",
          info: "9.9",
          user: "49.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4zVlh/hzace79wlr/eLd8UzzCyPOnKFc6bh14tk&filename=th2",
          title: "사장님의 특별지시",
          info: "9.9",
          user: "41.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bOkrb8/hzp2j6CvOQ/kbjxtdpkNHpQZpmThVLos1&filename=th2",
          title: "사내 맞선",
          info: "10.0",
          user: "198.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=52JL3/hyZ8D4ijJj/5l1NJOM5nAeWLHVkZpVFM0&filename=th2",
          title: "용, 감한 연애",
          info: "9.8",
          user: "30.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bHcP0X/hzhOiO3GzX/TskY2u0bY2elhyZ8spdFd0&filename=th2",
          title: "천하제일 표사",
          info: "9.6",
          user: "16.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bCVX6Q/hyATuqpQ2h/RGNsYqdzi79pTwbKdyGmT0&filename=th2",
          title: "학사재생",
          info: "9.9",
          user: "167.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cr2Kc9/hzb7ycnmms/tm18dfsnOsvzzyORUJaUP1&filename=th2",
          title: "신마",
          info: "9.2",
          user: "8.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ci204O/hzp2fXpq0c/kJYIUtWhdIWWczAEIGftD1&filename=th2",
          title: "하필이면 까마귀가 되어버렸다",
          info: "1위",
          user: "33.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "9.9",
          user: "57.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cXUoze/hy41PZ2lMh/DdS2BlmZjHKkMUCEvBHC71&filename=th2",
          title: "다시 한번 아이돌",
          info: "9.9",
          user: "37.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwUHkQ/hzhOeFwHdS/EhHwSjL3h1svCK6RExMO61&filename=th2",
          title: "월요일이 사라졌다",
          info: "9.9",
          user: "11.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dYU8b/hzb7xxhnSp/Da0aUtvYVY3c19FuUz0oK1&filename=th2",
          title: "막장드라마의 제왕",
          info: "9.9",
          user: "28.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=drGb4/hzhOjGWQak/dE94GJ4Cle0loMEKl7nX0K&filename=th2",
          title: "가족이 되는 방법",
          info: "10.0",
          user: "20.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "4위",
          user: "57.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4zVlh/hzace79wlr/eLd8UzzCyPOnKFc6bh14tk&filename=th2",
          title: "사장님의 특별지시",
          info: "5위",
          user: "41.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhe9o7/hzmU3zpvL3/DWRcsmPxJAlrjDw7MkGWwK&filename=th2",
          title: "8클래스 마법사의 회귀",
          info: "9.9",
          user: "81.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cburiM/hy41PLVqom/1BQa5TQO17iJiSIsRTKVr0&filename=th2",
          title: "나는 이 집 아이",
          info: "9.9",
          user: "212만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bBN4dK/hzhOhvRXM4/ykApb2W8w90ILBWRgWANM0&filename=th2",
          title: "악당과 계약 가족이 되었다",
          info: "10.0",
          user: "49.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=drGb4/hzhOjGWQak/dE94GJ4Cle0loMEKl7nX0K&filename=th2",
          title: "가족이 되는 방법",
          info: "10.0",
          user: "20.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bNhW1e/hzb7AOZqwu/Nvdfc6TfhUnn9CBNuUijq1&filename=th2",
          title: "뒤끝작렬",
          info: "4위",
          user: "57.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4zVlh/hzace79wlr/eLd8UzzCyPOnKFc6bh14tk&filename=th2",
          title: "사장님의 특별지시",
          info: "5위",
          user: "41.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhe9o7/hzmU3zpvL3/DWRcsmPxJAlrjDw7MkGWwK&filename=th2",
          title: "8클래스 마법사의 회귀",
          info: "9.9",
          user: "81.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bHcP0X/hzhOiO3GzX/TskY2u0bY2elhyZ8spdFd0&filename=th2",
          title: "천하제일 표사",
          info: "9.6",
          user: "16.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bCVX6Q/hyATuqpQ2h/RGNsYqdzi79pTwbKdyGmT0&filename=th2",
          title: "학사재생",
          info: "9.9",
          user: "167.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bEZGwb/hyQ9UfEEiQ/Hpt0oUWQfjX3lQbt2816wk&filename=th2",
          title: "유리의 성",
          info: "10.0",
          user: "42.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cSoIgy/hy41H00NFE/juIgEt25Th0lkY0C9SMhe1&filename=th2",
          title: "나를 기억하나요",
          info: "9.8",
          user: "55만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dpadT7/hzhOgqBSHA/HpZA6H7vPawsODuGIQaQO0&filename=th2",
          title: "이번 생은 가주가 되겠습니다",
          info: "2위",
          user: "122.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bhaZNx/hzhOgKHpz7/xbaDBtEqubGcBNaJ6pdta1&filename=th2",
          title: "남주를 주웠더니 남편이 생겨버렸다",
          info: "3위",
          user: "51.4만명",
        },
      ],
    ],
  },
  {
    category: "기대 신작 TOP",
    cardStyle: 1,
    divByDay: false,
    data: {
      img: "//dn-img-page.kakao.com/download/resource?kid=cmJs9e/hzmU3MYOek/31ARHCsiGEuowXs4jk43b1",
      title: "나도 그들처럼 영웅이 되고 싶었다.",
    },
  },
  {
    category: "로맨스 TOP",
    cardStyle: 0,
    divByDay: false,
    data: [
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=bkV7n3/hy41OF0bDR/A9qKNVg2e3aAT3haZc5QWk&filename=th2",
        title: "익애~ 봉황애사~",
        info: "10.0",
        user: "49.6만명",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
        title: "상사가 나를 덕질한다",
        info: "9.8",
        user: "24.1만명",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
        title: "쓰라는 글은 안쓰고",
        info: "9.9",
        user: "22.1만명",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=S4Ss5/hy41FP1JZI/xqCOyfM19jcgdBbUkflNKK&filename=th2",
        title: "열세 번째 밤",
        info: "9.8",
        user: "43.3만명",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=cryGFr/hyCveyNFAy/AxEAcNtMvApipXvPOWrrfK&filename=th2",
        title: "이 봄을 갖고 싶다",
        info: "9.6",
        user: "67만명",
      },
    ],
  },
  {
    category: "일간 랭킹 TOP",
    cardStyle: 2,
    divByDay: false,
    data: [
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=CHb7E/hzmU2NVBFU/3xX6JB8B7kKFohHzH9LJtk&filename=th2",
        title: "흑막을 버리는 데 실패했다",
        info: "28.7만명 | 기다무웹툰 | 로판 | ASSAM,쓩늉,자은",
        day: "수 연재",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=eVtdO/hzmU2tEBKW/VuaxFpaYkAsyGg2tUoNJKk&filename=th2",
        title: "이번 생은 가주가 되겠습니다",
        info: "122.6만명 | 기다무웹툰 | 로판 | 앤트스튜디오,몬,앤트스튜디오,김로아",
        day: "수 연재",
      },
      {
        img: "//dn-img-page.kakao.com/download/resource?kid=cR1QGX/hzmU0WFP2T/kUMEn3fFoyhP9rFxck2mkK&filename=th2",
        title: "남주를 주웠더니 남편이 생겨버렸다",
        info: "51만명 | 기다무웹툰 | 로판 | 마리씨,서촌,초암",
        day: "월 연재",
      },
    ],
  },
  {
    category: "추천 이벤트",
    cardStyle: 3,
    divByDay: false,
    data: {
      img: "//dn-img-page.kakao.com/download/resource?kid=jySqs/hzmU1hjQwo/MUcpK0XEI9k4AfWbJBfkZk",
    },
  },
];

const dailySerData = [
  {
    cardStyle: 0,
    divByDay: true,
    data: [
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=zyDgA/hzhOfyr7h4/TnEdnMTNLrPgSehcKJIOek&filename=th2",
          title: "인간시장",
          info: "9.9",
          user: "22만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=tWHg6/hzhOj8nH2D/e46KHq3CYbDhDvLIlpFrZK&filename=th2",
          title: "에스티오",
          info: "9.9",
          user: "32.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJvRjt/hzmU0WmgRd/YRYAYBF6WZ2qQNH4IBafw0&filename=th2",
          title: "돈빵",
          info: "9.5",
          user: "8.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },

        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cYHX9j/hzhOeZ2ihH/6hDyft2Ke9UYkrGv6RVgU0&filename=th2",
          title: "이번 생은 제대로 키워 드리겠습니다, 폐하!",
          info: "10.0",
          user: "26.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ymPhi/hzb7vmxptr/aOBSlgRdCuKlmW581yVbRk&filename=th2",
          title: "디어 마이 프렌드",
          info: "9.0",
          user: "26.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4pT3F/hyLi76skGR/u3m5gW9VYP1mP6xNTTAafk&filename=th2",
          title: "로드 오브 머니",
          info: "9.9",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "1위",
          user: "202만명",
        },

        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c2DSEf/hzb7w6zKtd/UK9WqhIqkQeuuaEWVibth0&filename=th2",
          title: "엑스텐",
          info: "9.9",
          user: "7.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bSs9ny/hyF229DBry/K5dGwwU7jcYtD9SuB4NBVk&filename=th2",
          title: "화우요 [BL]",
          info: "9.9",
          user: "20.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bXsBYJ/hzp2nuj2R1/J47A3g3iQGY1ilwoGu3zA0&filename=th2",
          title: "수상한 동거 [개정판]",
          info: "9.6",
          user: "5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cGEiH/hyEddlyyun/d9SIWb2NMFeEOjs1FbkYEk&filename=th2",
          title: "용이 비를 내리는 나라",
          info: "10.0",
          user: "106만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
          title: "바람이 머무는 자리 [BL]",
          info: "9.9",
          user: "14.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hGkV0/hyZ8tNQtRA/s0oHoWpiDrk65owacgh5bk&filename=th2",
          title: "엔네아드 (ENNEAD)",
          info: "10.0",
          user: "22.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "9.9",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hnOHU/hzp2dZq5n7/jqpTvIbZzFwiD3HkNXklok&filename=th2",
          title: "힐통령 - 태양의 사제",
          info: "9.8",
          user: "18.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cEXgMa/hyATr1CZmD/YoDlK2IoUrelLh02Ria3f1&filename=th2",
          title: "던전 리셋",
          info: "9.9",
          user: "71.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bXsBYJ/hzp2nuj2R1/J47A3g3iQGY1ilwoGu3zA0&filename=th2",
          title: "수상한 동거 [개정판]",
          info: "9.6",
          user: "5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cGEiH/hyEddlyyun/d9SIWb2NMFeEOjs1FbkYEk&filename=th2",
          title: "용이 비를 내리는 나라",
          info: "10.0",
          user: "106만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
          title: "바람이 머무는 자리 [BL]",
          info: "9.9",
          user: "14.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hGkV0/hyZ8tNQtRA/s0oHoWpiDrk65owacgh5bk&filename=th2",
          title: "엔네아드 (ENNEAD)",
          info: "10.0",
          user: "22.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "1위",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cYHX9j/hzhOeZ2ihH/6hDyft2Ke9UYkrGv6RVgU0&filename=th2",
          title: "이번 생은 제대로 키워 드리겠습니다, 폐하!",
          info: "10.0",
          user: "26.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ymPhi/hzb7vmxptr/aOBSlgRdCuKlmW581yVbRk&filename=th2",
          title: "디어 마이 프렌드",
          info: "9.0",
          user: "26.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4pT3F/hyLi76skGR/u3m5gW9VYP1mP6xNTTAafk&filename=th2",
          title: "로드 오브 머니",
          info: "9.9",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=zyDgA/hzhOfyr7h4/TnEdnMTNLrPgSehcKJIOek&filename=th2",
          title: "인간시장",
          info: "9.9",
          user: "22만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=tWHg6/hzhOj8nH2D/e46KHq3CYbDhDvLIlpFrZK&filename=th2",
          title: "에스티오",
          info: "9.9",
          user: "32.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJvRjt/hzmU0WmgRd/YRYAYBF6WZ2qQNH4IBafw0&filename=th2",
          title: "돈빵",
          info: "9.5",
          user: "8.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c2DSEf/hzb7w6zKtd/UK9WqhIqkQeuuaEWVibth0&filename=th2",
          title: "엑스텐",
          info: "9.9",
          user: "7.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bSs9ny/hyF229DBry/K5dGwwU7jcYtD9SuB4NBVk&filename=th2",
          title: "화우요 [BL]",
          info: "9.9",
          user: "20.5만명",
        },

        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "9.9",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hnOHU/hzp2dZq5n7/jqpTvIbZzFwiD3HkNXklok&filename=th2",
          title: "힐통령 - 태양의 사제",
          info: "9.8",
          user: "18.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cEXgMa/hyATr1CZmD/YoDlK2IoUrelLh02Ria3f1&filename=th2",
          title: "던전 리셋",
          info: "9.9",
          user: "71.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cYHX9j/hzhOeZ2ihH/6hDyft2Ke9UYkrGv6RVgU0&filename=th2",
          title: "이번 생은 제대로 키워 드리겠습니다, 폐하!",
          info: "10.0",
          user: "26.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ymPhi/hzb7vmxptr/aOBSlgRdCuKlmW581yVbRk&filename=th2",
          title: "디어 마이 프렌드",
          info: "9.0",
          user: "26.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4pT3F/hyLi76skGR/u3m5gW9VYP1mP6xNTTAafk&filename=th2",
          title: "로드 오브 머니",
          info: "9.9",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "1위",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=zyDgA/hzhOfyr7h4/TnEdnMTNLrPgSehcKJIOek&filename=th2",
          title: "인간시장",
          info: "9.9",
          user: "22만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=tWHg6/hzhOj8nH2D/e46KHq3CYbDhDvLIlpFrZK&filename=th2",
          title: "에스티오",
          info: "9.9",
          user: "32.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJvRjt/hzmU0WmgRd/YRYAYBF6WZ2qQNH4IBafw0&filename=th2",
          title: "돈빵",
          info: "9.5",
          user: "8.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c2DSEf/hzb7w6zKtd/UK9WqhIqkQeuuaEWVibth0&filename=th2",
          title: "엑스텐",
          info: "9.9",
          user: "7.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bSs9ny/hyF229DBry/K5dGwwU7jcYtD9SuB4NBVk&filename=th2",
          title: "화우요 [BL]",
          info: "9.9",
          user: "20.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bXsBYJ/hzp2nuj2R1/J47A3g3iQGY1ilwoGu3zA0&filename=th2",
          title: "수상한 동거 [개정판]",
          info: "9.6",
          user: "5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cGEiH/hyEddlyyun/d9SIWb2NMFeEOjs1FbkYEk&filename=th2",
          title: "용이 비를 내리는 나라",
          info: "10.0",
          user: "106만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
          title: "바람이 머무는 자리 [BL]",
          info: "9.9",
          user: "14.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hGkV0/hyZ8tNQtRA/s0oHoWpiDrk65owacgh5bk&filename=th2",
          title: "엔네아드 (ENNEAD)",
          info: "10.0",
          user: "22.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "9.9",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hnOHU/hzp2dZq5n7/jqpTvIbZzFwiD3HkNXklok&filename=th2",
          title: "힐통령 - 태양의 사제",
          info: "9.8",
          user: "18.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cEXgMa/hyATr1CZmD/YoDlK2IoUrelLh02Ria3f1&filename=th2",
          title: "던전 리셋",
          info: "9.9",
          user: "71.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "1위",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cYHX9j/hzhOeZ2ihH/6hDyft2Ke9UYkrGv6RVgU0&filename=th2",
          title: "이번 생은 제대로 키워 드리겠습니다, 폐하!",
          info: "10.0",
          user: "26.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ymPhi/hzb7vmxptr/aOBSlgRdCuKlmW581yVbRk&filename=th2",
          title: "디어 마이 프렌드",
          info: "9.0",
          user: "26.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4pT3F/hyLi76skGR/u3m5gW9VYP1mP6xNTTAafk&filename=th2",
          title: "로드 오브 머니",
          info: "9.9",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=zyDgA/hzhOfyr7h4/TnEdnMTNLrPgSehcKJIOek&filename=th2",
          title: "인간시장",
          info: "9.9",
          user: "22만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=tWHg6/hzhOj8nH2D/e46KHq3CYbDhDvLIlpFrZK&filename=th2",
          title: "에스티오",
          info: "9.9",
          user: "32.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJvRjt/hzmU0WmgRd/YRYAYBF6WZ2qQNH4IBafw0&filename=th2",
          title: "돈빵",
          info: "9.5",
          user: "8.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c2DSEf/hzb7w6zKtd/UK9WqhIqkQeuuaEWVibth0&filename=th2",
          title: "엑스텐",
          info: "9.9",
          user: "7.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bSs9ny/hyF229DBry/K5dGwwU7jcYtD9SuB4NBVk&filename=th2",
          title: "화우요 [BL]",
          info: "9.9",
          user: "20.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bXsBYJ/hzp2nuj2R1/J47A3g3iQGY1ilwoGu3zA0&filename=th2",
          title: "수상한 동거 [개정판]",
          info: "9.6",
          user: "5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cGEiH/hyEddlyyun/d9SIWb2NMFeEOjs1FbkYEk&filename=th2",
          title: "용이 비를 내리는 나라",
          info: "10.0",
          user: "106만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
          title: "바람이 머무는 자리 [BL]",
          info: "9.9",
          user: "14.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hGkV0/hyZ8tNQtRA/s0oHoWpiDrk65owacgh5bk&filename=th2",
          title: "엔네아드 (ENNEAD)",
          info: "10.0",
          user: "22.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "9.9",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hnOHU/hzp2dZq5n7/jqpTvIbZzFwiD3HkNXklok&filename=th2",
          title: "힐통령 - 태양의 사제",
          info: "9.8",
          user: "18.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cEXgMa/hyATr1CZmD/YoDlK2IoUrelLh02Ria3f1&filename=th2",
          title: "던전 리셋",
          info: "9.9",
          user: "71.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cYHX9j/hzhOeZ2ihH/6hDyft2Ke9UYkrGv6RVgU0&filename=th2",
          title: "이번 생은 제대로 키워 드리겠습니다, 폐하!",
          info: "10.0",
          user: "26.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=ymPhi/hzb7vmxptr/aOBSlgRdCuKlmW581yVbRk&filename=th2",
          title: "디어 마이 프렌드",
          info: "9.0",
          user: "26.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=4pT3F/hyLi76skGR/u3m5gW9VYP1mP6xNTTAafk&filename=th2",
          title: "로드 오브 머니",
          info: "9.9",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=zyDgA/hzhOfyr7h4/TnEdnMTNLrPgSehcKJIOek&filename=th2",
          title: "인간시장",
          info: "9.9",
          user: "22만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=tWHg6/hzhOj8nH2D/e46KHq3CYbDhDvLIlpFrZK&filename=th2",
          title: "에스티오",
          info: "9.9",
          user: "32.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJvRjt/hzmU0WmgRd/YRYAYBF6WZ2qQNH4IBafw0&filename=th2",
          title: "돈빵",
          info: "9.5",
          user: "8.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c2DSEf/hzb7w6zKtd/UK9WqhIqkQeuuaEWVibth0&filename=th2",
          title: "엑스텐",
          info: "9.9",
          user: "7.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bSs9ny/hyF229DBry/K5dGwwU7jcYtD9SuB4NBVk&filename=th2",
          title: "화우요 [BL]",
          info: "9.9",
          user: "20.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bXsBYJ/hzp2nuj2R1/J47A3g3iQGY1ilwoGu3zA0&filename=th2",
          title: "수상한 동거 [개정판]",
          info: "9.6",
          user: "5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "1위",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cGEiH/hyEddlyyun/d9SIWb2NMFeEOjs1FbkYEk&filename=th2",
          title: "용이 비를 내리는 나라",
          info: "10.0",
          user: "106만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bbt9Th/hzp2g9TEUj/1jDKRYqDbJPRHqV1TZRF80&filename=th2",
          title: "골드 그레이(Gold gray)",
          info: "9.9",
          user: "22.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
          title: "바람이 머무는 자리 [BL]",
          info: "9.9",
          user: "14.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hGkV0/hyZ8tNQtRA/s0oHoWpiDrk65owacgh5bk&filename=th2",
          title: "엔네아드 (ENNEAD)",
          info: "10.0",
          user: "22.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
          title: "도굴왕",
          info: "9.9",
          user: "202만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=hnOHU/hzp2dZq5n7/jqpTvIbZzFwiD3HkNXklok&filename=th2",
          title: "힐통령 - 태양의 사제",
          info: "9.8",
          user: "18.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cEXgMa/hyATr1CZmD/YoDlK2IoUrelLh02Ria3f1&filename=th2",
          title: "던전 리셋",
          info: "9.9",
          user: "71.5만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
      [
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
          title: "프로야구생존기",
          info: "9.9",
          user: "17.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=BhuyZ/hzmU28erVj/kKCWrVtehqyy7QaqvBS1m0&filename=th2",
          title: "달 아래에서 만나다",
          info: "9.8",
          user: "22.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cTTZMV/hzhOlduqrV/XVzRKIJCdlg4slfZFnTKnK&filename=th2",
          title: "쓰라는 글은 안 쓰고",
          info: "9.9",
          user: "22.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c8tCco/hzp2gIUWxt/ry3ItGAfPNAl5fwqnJ74B1&filename=th2",
          title: "익애 ~봉황애사~",
          info: "10.0",
          user: "49.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=duehr/hzp2nAV7j9/tGDMKb1kRIdnO6D50v8E0K&filename=th2",
          title: "악녀를 죽여 줘",
          info: "2위",
          user: "69.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "3위",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cRT27X/hzb7xkvb7b/Aqq7Dg18kl4JNephTEoqXK&filename=th2",
          title: "다정한 그대를 지키는 방법",
          info: "10.0",
          user: "89.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=cppzaC/hzp2ifvC1J/IAy6e8p17VpMjWaIfr3bkK&filename=th2",
          title: "막내 황녀님",
          info: "9.9",
          user: "118.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=qnE7v/hzb7xKF0sd/QKoyuFgYDkf53tKkWcm2yk&filename=th2",
          title: "빈껍데기 공작부인",
          info: "10.0",
          user: "147만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=eH0mbP/hzp2m3kTd1/vYzzIRp1boG2MeWl3AFUhk&filename=th2",
          title: "이 용사 실화냐",
          info: "9.4",
          user: "18.1만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=HibaU/hzhOlEId3G/2JFXU3ToSRrIYOkIHrw4kk&filename=th2",
          title: "부서진 성좌의 회귀",
          info: "9.8",
          user: "18.6만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bJ9TFT/hzmU1g5Qiq/fcap9qWuChIKBzcs6zYd40&filename=th2",
          title: "상사가 나를 덕질한다",
          info: "9.8",
          user: "27.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=wzypj/hzb7weqTcH/jKk47zRvKcy70uyRapFbsk&filename=th2",
          title: "인별당",
          info: "9.9",
          user: "19.2만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=S7bzf/hyLjeEmZON/Z5FdkWTDdvJAfOKnFJ8au1&filename=th2",
          title: "그곳에, 네가[독점연재]",
          info: "9.8",
          user: "17.7만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=buFJDf/hzb7rKB44w/1dAWermHRTJPW3iLyVGlIk&filename=th2",
          title: "악녀는 두 번 산다",
          info: "10.0",
          user: "104.9만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=bujpXE/hzp2dkXhhM/Mu7WpXkD00LxrI4448tPEK&filename=th2",
          title: "병약한? 남편의 계약 아내",
          info: "9.5",
          user: "27.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dAwU0d/hzacdOk9GR/W0v5wU5mb8boVWJLghJuW0&filename=th2",
          title: "나의 자리",
          info: "9.8",
          user: "25.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=3hlBc/hzmU2msy5o/yS4Orh8GldIjV9x1AEJBY1&filename=th2",
          title: "집착 서브 남주를 키웠습니다",
          info: "10.0",
          user: "41.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=pw32S/hzhOgKyZGa/Sn5Z1dlG6XVyzgLM3vikPK&filename=th2",
          title: "지옥에서 독식",
          info: "8.4",
          user: "17.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=dwMIuC/hzhOgD8UFe/J6wGhV1I0sWJ4jwJvUYun1&filename=th2",
          title: "화타가 된 외과의사",
          info: "9.8",
          user: "28.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=biG4Nt/hzb7sXLBzm/Spy2JkLBLu3zUwNl9TaznK&filename=th2",
          title: "궁귀검신",
          info: "9.8",
          user: "51.8만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=9SrAa/hyQ9K5lt8c/ScWhRmPT5Cf47ANpwUlTkK&filename=th2",
          title: "무인이곽",
          info: "9.7",
          user: "26만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=uc4Yp/hzacfeRjkH/BuQSE1IDL6Kl9jJsF0siL0&filename=th2",
          title: "학사귀환",
          info: "9.6",
          user: "50.3만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=c4r7d2/hyQ9UGblzI/YvMysNUb1IBUcCRwKAlRFK&filename=th2",
          title: "트리거",
          info: "9.9",
          user: "55.4만명",
        },
        {
          img: "https://dn-img-page.kakao.com/download/resource?kid=W9plG/hyCvhI2fGW/OAld3JoQkLtKZbhbDzk02k&filename=th2",
          title: "아비무쌍",
          info: "9.9",
          user: "73.8만명",
        },
      ],
    ],
  },
];

const carouselData = [
  [
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=WOEgA/hzmU0Jxe7C/mbKCTR9na3asOM5IfnhJv1",
      title: "사내 맞선",
      user: "201.3만명",
      script: "사장님과 맞선을? 들키면 해고다!",
    },
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=xQfci/hzp2lDl8mg/i7ukSZCV1OKMyxZ7RxnQAK",
      title: "도굴왕",
      user: "201.4만명",
      script: "여기도 '그 자식'이 다 털어갔냐?",
    },
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=mNfwc/hzb7spege4/7ecXCccjHbpBOTc04piG10",
      title: "막장드라마의 제왕",
      user: "28.8만명",
      script: "진정한 막장의 끝을 보여주겠다!",
    },
  ],
  [
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=8DKKH/hzb7vmuOzN/ow4zohQpKLrBJhJf9gb730",
      title: "레벨업 못하는 플레이어",
      user: "71.8만명",
      script: "레벨업? 좀 못해도 상관없잖아!",
    },
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=vRYid/hzp2jyNeO9/OnE0dQAZAvpZr3mDMm07ik",
      title: "천하제일 표사",
      user: "17.7만명",
      script: "최강 표국을 세우기 위해 뭉쳤다!",
    },
    {
      img: "//dn-img-page.kakao.com/download/resource?kid=ULyKN/hyZ8vj5vsN/8BFKK0vJXdpgCZrgHyehNk",
      title: "학사재생",
      user: "167.8만명",
      script: "천하제일의 사내, 금수저 물고 환생?",
    },
  ],
];

export { homeData, dailySerData, carouselData };
