const webtoons = [
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=c9BidG/hzhOhJV5W3/ApkqR0bIKHmF8faTtNCm60&filename=th2",
    title: "남편님, 다시 결혼해 주세요!",
    info: "1위",
    user: "31.3만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
    title: "도굴왕",
    info: "2위",
    user: "201.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=2XcHF/hzacfyyDaP/AQvywUuQOQ9bmwXoyvCKbK&filename=th2",
    title: "SSS급 죽어야 사는 헌터",
    info: "3위",
    user: "92.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=1dqit/hy41OzZK0J/q0M4m4gLW2Zjm4mmKkglI1&filename=th2",
    title: "남편이 미모를 숨김",
    info: "10.0",
    user: "125.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cbjtkI/hzacgYFTkq/PSAiujZt9kOXMOPj1XT7LK&filename=th2",
    title: "백작가의 망나니가 되었다",
    info: "10.0",
    user: "131.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=rXsr4/hy41LCCbZh/fBVAe3YWcZVU3fOL0tJxPk&filename=th2",
    title: "화홍",
    info: "9.8",
    user: "113.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=deE4e2/hzmU2gb3TS/51FXKvnkpArAKzgyHv1fWk&filename=th2",
    title: "너의 죽음이 보여",
    info: "10.0",
    user: "35.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cyq0ma/hzb7yDg2ke/bIzebxQnLC3RJj7mkrwcUK&filename=th2",
    title: "비뢰도",
    info: "9.8",
    user: "104.2만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
    title: "프로야구생존기",
    info: "9.9",
    user: "17.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2",
    title: "누구의 아이를 낳을까",
    info: "9.7",
    user: "26.5만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=b60gs5/hyQ9S2BUwT/Vv2RtbZab85B2G8UKpaxX0&filename=th2",
    title: "미필적 고의에 의한 관계",
    info: "9.8",
    user: "35.2만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=rXsr4/hy41LCCbZh/fBVAe3YWcZVU3fOL0tJxPk&filename=th2",
    title: "화홍",
    info: "9.8",
    user: "113.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=dhtiUZ/hyF25MjaRn/00ifT9ywyqgoucJ3lNJqfk&filename=th2",
    title: "절대갑 길들이기",
    info: "9.8",
    user: "43.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=NLHxs/hyATqIqH5s/PpwvwZDgLceAgfCkQBZBaK&filename=th2",
    title: "나의 나쁜 연하남",
    info: "9.8",
    user: "40.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cZm0Av/hzaccvAwr7/jzETXA87pKpmKioKLASEik&filename=th2",
    title: "천 개의 달이 뜨면",
    info: "9.9",
    user: "25.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2",
    title: "미연시 게임 속 하찮은 엑스트라",
    info: "9.8",
    user: "23.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=sA4wJ/hzmU2G6zLw/t1L9MrZkkNCS6BE9IkO6s0&filename=th2",
    title: "황녀님이 사악하셔",
    info: "9.9",
    user: "44.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=6MBzg/hzb7AareJR/olV7dxkZi3pni7xrRZ57Nk&filename=th2",
    title: "폭군의 누나로 산다는 것은[독점연재]",
    info: "9.9",
    user: "64.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=c6NsaC/hyZ8BkSTF6/rUUeLNIYEPttoAsEpvfAz0&filename=th2",
    title: "그녀가 악녀로 사는 이유",
    info: "9.8",
    user: "37.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=deE4e2/hzmU2gb3TS/51FXKvnkpArAKzgyHv1fWk&filename=th2",
    title: "너의 죽음이 보여",
    info: "10.0",
    user: "35.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=dLwIj/hzb7AHL1rJ/u6iymPdnftI3S6fZ9QKel0&filename=th2",
    title: "유리의 벽",
    info: "10.0",
    user: "44.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cNvc0Z/hzhOdU4aI9/5WoMJ99qAUSzv49grq9SK0&filename=th2",
    title: "톱스타, 그 자체",
    info: "9.9",
    user: "6.9만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=CLJBa/hyATqn0Q3p/xPvmPoA8nEKeYkZKdMlyy0&filename=th2",
    title: "은동은동+옹동스",
    info: "10.0",
    user: "46.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=Me51U/hyLjf383Rf/3FcQumeyIKc5wuIk1FIHS0&filename=th2",
    title: "치트라",
    info: "10.0",
    user: "114만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=q0TyC/hzb7ycEw86/2iGD9tBanfdVoigRoJsi9k&filename=th2",
    title: "씨름의 희열",
    info: "9.8",
    user: "11.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cqZA0V/hzacd84mNX/s3PtIZmocIWK7ABeG0ac31&filename=th2",
    title: "어딜 봐요 매니저님",
    info: "9.8",
    user: "18.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=c3xG5E/hzhOohQOpW/KoaGkWzM6mK9TPOIb2wbE0&filename=th2",
    title: "경계인",
    info: "9.9",
    user: "9.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=Ng7NH/hzmU3FJuxF/kJSdVfRnPwuodY65V1mfAK&filename=th2",
    title: "네크로맨서 생존기",
    info: "10.0",
    user: "4.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
    title: "바람이 머무는 자리 [BL]",
    info: "9.9",
    user: "14.3만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bWRnqq/hy41LwsibS/tFl0ThHhYEwCWrTjyk2U2k&filename=th2",
    title: "우연한 친구",
    info: "9.8",
    user: "9만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bhEjzw/hzhOfkJ4Le/Qk9yTzliowfFfy7i3lSYfK&filename=th2",
    title: "나쁜 색기 [개정판]",
    info: "9.5",
    user: "6.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=ctCkD/hzb7tJc8VV/jiKt3fW8PAFAxcarKHhV0k&filename=th2",
    title: "플러그 인(Plug in)",
    info: "9.6",
    user: "5.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=oNdZh/hzp2dSFpCH/DpjgRsigIt3bTDgGL9YHFk&filename=th2",
    title: "[연재] 해 밝은 밤의 산책",
    info: "9.7",
    user: "8.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
    title: "도굴왕",
    info: "9.9",
    user: "201.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
    title: "아빠가 너무 강함",
    info: "9.8",
    user: "48.5만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cZKvZ/hzhOohFebJ/TyLCxTLzJHwYtda5F9rJZk&filename=th2",
    title: "이차원 용병",
    info: "9.9",
    user: "103.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cAKTeD/hzp2jFi7xz/KlJNkqgdjEzpyUZfbKtYCK&filename=th2",
    title: "BJ대마도사",
    info: "9.9",
    user: "26.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=RVjif/hyQ9Nulmj3/de4SxKZarIui9bHh1iKWtk&filename=th2",
    title: "라이프 크라이",
    info: "9.2",
    user: "16만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=wQKSm/hzb7tBTJkq/FTLtqYnKNiZUNaCz5uX6NK&filename=th2",
    title: "서울역 네크로맨서",
    info: "9.6",
    user: "30.3만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cyq0ma/hzb7yDg2ke/bIzebxQnLC3RJj7mkrwcUK&filename=th2",
    title: "비뢰도",
    info: "9.8",
    user: "104.2만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bxwSRj/hyZ8Cqaolk/a6g8xe598ercCD3GIw0Ktk&filename=th2",
    title: "생사결: 여래의 복수",
    info: "9.8",
    user: "58.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=O2gvI/hy41MPonM0/exDflmPQEKmkXbFHoWjRsk&filename=th2",
    title: "호위무사",
    info: "9.7",
    user: "23.5만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=iv9T2/hzb7z2PmnI/JoRAAiCICwHk79E5ADPQuK&filename=th2",
    title: "천년방사",
    info: "9.8",
    user: "21.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bJuuTB/hzp2drIoFq/1tknNZA6KK66T1qgElQlYK&filename=th2",
    title: "전왕",
    info: "9.3",
    user: "10.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=I3jTP/hzb7z95PAx/AJ86JUq8DwmN6UacJTFb7K&filename=th2",
    title: "종횡구주",
    info: "8.7",
    user: "12.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cbjtkI/hzacgYFTkq/PSAiujZt9kOXMOPj1XT7LK&filename=th2",
    title: "백작가의 망나니가 되었다",
    info: "10.0",
    user: "131.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=rXsr4/hy41LCCbZh/fBVAe3YWcZVU3fOL0tJxPk&filename=th2",
    title: "화홍",
    info: "9.8",
    user: "113.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=deE4e2/hzmU2gb3TS/51FXKvnkpArAKzgyHv1fWk&filename=th2",
    title: "너의 죽음이 보여",
    info: "10.0",
    user: "35.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cyq0ma/hzb7yDg2ke/bIzebxQnLC3RJj7mkrwcUK&filename=th2",
    title: "비뢰도",
    info: "9.8",
    user: "104.2만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=mLxer/hyZ8xiGrsa/lo9hJND6wYN5T51AklU2V0&filename=th2",
    title: "프로야구생존기",
    info: "9.9",
    user: "17.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=lLRDp/hzb7uHbYRi/3aMKXm2PXLc62IZKWBOSak&filename=th2",
    title: "누구의 아이를 낳을까",
    info: "9.7",
    user: "26.5만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=b60gs5/hyQ9S2BUwT/Vv2RtbZab85B2G8UKpaxX0&filename=th2",
    title: "미필적 고의에 의한 관계",
    info: "9.8",
    user: "35.2만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=rXsr4/hy41LCCbZh/fBVAe3YWcZVU3fOL0tJxPk&filename=th2",
    title: "화홍",
    info: "9.8",
    user: "113.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=dhtiUZ/hyF25MjaRn/00ifT9ywyqgoucJ3lNJqfk&filename=th2",
    title: "절대갑 길들이기",
    info: "9.8",
    user: "43.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=NLHxs/hyATqIqH5s/PpwvwZDgLceAgfCkQBZBaK&filename=th2",
    title: "나의 나쁜 연하남",
    info: "9.8",
    user: "40.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cZm0Av/hzaccvAwr7/jzETXA87pKpmKioKLASEik&filename=th2",
    title: "천 개의 달이 뜨면",
    info: "9.9",
    user: "25.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=czz1LH/hzhOdNxBuR/13Yh4xVNddVTlBceG9PgvK&filename=th2",
    title: "미연시 게임 속 하찮은 엑스트라",
    info: "9.8",
    user: "23.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=sA4wJ/hzmU2G6zLw/t1L9MrZkkNCS6BE9IkO6s0&filename=th2",
    title: "황녀님이 사악하셔",
    info: "9.9",
    user: "44.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=6MBzg/hzb7AareJR/olV7dxkZi3pni7xrRZ57Nk&filename=th2",
    title: "폭군의 누나로 산다는 것은[독점연재]",
    info: "9.9",
    user: "64.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=c6NsaC/hyZ8BkSTF6/rUUeLNIYEPttoAsEpvfAz0&filename=th2",
    title: "그녀가 악녀로 사는 이유",
    info: "9.8",
    user: "37.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=deE4e2/hzmU2gb3TS/51FXKvnkpArAKzgyHv1fWk&filename=th2",
    title: "너의 죽음이 보여",
    info: "10.0",
    user: "35.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=dLwIj/hzb7AHL1rJ/u6iymPdnftI3S6fZ9QKel0&filename=th2",
    title: "유리의 벽",
    info: "10.0",
    user: "44.7만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cNvc0Z/hzhOdU4aI9/5WoMJ99qAUSzv49grq9SK0&filename=th2",
    title: "톱스타, 그 자체",
    info: "9.9",
    user: "6.9만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=CLJBa/hyATqn0Q3p/xPvmPoA8nEKeYkZKdMlyy0&filename=th2",
    title: "은동은동+옹동스",
    info: "10.0",
    user: "46.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=Me51U/hyLjf383Rf/3FcQumeyIKc5wuIk1FIHS0&filename=th2",
    title: "치트라",
    info: "10.0",
    user: "114만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=q0TyC/hzb7ycEw86/2iGD9tBanfdVoigRoJsi9k&filename=th2",
    title: "씨름의 희열",
    info: "9.8",
    user: "11.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cqZA0V/hzacd84mNX/s3PtIZmocIWK7ABeG0ac31&filename=th2",
    title: "어딜 봐요 매니저님",
    info: "9.8",
    user: "18.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=c3xG5E/hzhOohQOpW/KoaGkWzM6mK9TPOIb2wbE0&filename=th2",
    title: "경계인",
    info: "9.9",
    user: "9.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=Ng7NH/hzmU3FJuxF/kJSdVfRnPwuodY65V1mfAK&filename=th2",
    title: "네크로맨서 생존기",
    info: "10.0",
    user: "4.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=h7zzO/hyVkKmohi1/7tXwfbLOOjXY7dEeaMvOTK&filename=th2",
    title: "바람이 머무는 자리 [BL]",
    info: "9.9",
    user: "14.3만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bWRnqq/hy41LwsibS/tFl0ThHhYEwCWrTjyk2U2k&filename=th2",
    title: "우연한 친구",
    info: "9.8",
    user: "9만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=bhEjzw/hzhOfkJ4Le/Qk9yTzliowfFfy7i3lSYfK&filename=th2",
    title: "나쁜 색기 [개정판]",
    info: "9.5",
    user: "6.8만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=ctCkD/hzb7tJc8VV/jiKt3fW8PAFAxcarKHhV0k&filename=th2",
    title: "플러그 인(Plug in)",
    info: "9.6",
    user: "5.4만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=oNdZh/hzp2dSFpCH/DpjgRsigIt3bTDgGL9YHFk&filename=th2",
    title: "[연재] 해 밝은 밤의 산책",
    info: "9.7",
    user: "8.6만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cbOcrh/hzhOeyLVuz/o3mzWEkKKAuJOLWv6bYJxK&filename=th2",
    title: "도굴왕",
    info: "9.9",
    user: "201.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
    title: "아빠가 너무 강함",
    info: "9.8",
    user: "48.5만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cZKvZ/hzhOohFebJ/TyLCxTLzJHwYtda5F9rJZk&filename=th2",
    title: "이차원 용병",
    info: "9.9",
    user: "103.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=cAKTeD/hzp2jFi7xz/KlJNkqgdjEzpyUZfbKtYCK&filename=th2",
    title: "BJ대마도사",
    info: "9.9",
    user: "26.1만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=RVjif/hyQ9Nulmj3/de4SxKZarIui9bHh1iKWtk&filename=th2",
    title: "라이프 크라이",
    info: "9.2",
    user: "16만명",
  },
  {
    img: "https://dn-img-page.kakao.com/download/resource?kid=wQKSm/hzb7tBTJkq/FTLtqYnKNiZUNaCz5uX6NK&filename=th2",
    title: "서울역 네크로맨서",
    info: "9.6",
    user: "30.3만명",
  },
];

// webtoons.slice(0, 35).forEach((e) => {
//   webtoons.push(e);
// });

export { webtoons };
