export const DEFAULT_GENRE_INDEX = '1';
export const DEFAULT_PAGE = 'webtoon';
export const DEFAULT_GENRE = 'home';
export const START_SLIDE_INDEX = 0;
const week = ['sun','mon','tue','wed','thr','fri','sat']
export const DEFAULT_DAY = week[new Date().getDay()];
export const SLIDE_DELAY = '.5s'
export const SLIDE_CONTAINER_LENGTH = 3;
export const AUTO_SLIDE_INTERVAL = 3000;