export const WebtoonData = [
    {
      _id: 1,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5",
      genre: '드라마',
      rating: '10.0',
      ageLimit: 'All',
      week: ['월'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_new.svg?4ae84a0f972e30119fb6fcfbb2f59bf9",
    },
    {
      _id: 2,
      title: "천인의 신부",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bjVdJy/hyZ8tUUZ5V/skLruhRdIujVH996Dzxvw1&filename=th2",
      subscriptions: "48.5",
      genre: '드라마',
      rating: '9.5',
      ageLimit: 'All',
      week: ['화', '수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 3,
      title: "꼬마 영애님은 주연들을 길들인다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bQvfe8/hzb7yjh2WP/did3KdCAAbDrS0mgPk4tW0&filename=th2",
      subscriptions: "48.5",
      genre: '드라마',
      rating: '10.0',
      ageLimit: '15',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 4,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5",
      genre: '드라마',
      rating: '10.0',
      ageLimit: 'All',
      week: ['토'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 5,
      title: "이차원 용병",
      img: "http://dn-img-page.kakao.com/download/resource?kid=qklnd/hyCvm4LfZf/xUw9OCkXIPkU5eNV5nuMb0&filename=th2",
      subscriptions: "103",
      genre: '로맨스',
      rating: '9.7',
      ageLimit: 'All',
      week: ['일'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 6,
      title: "SSS급 죽어야 사는 헌터",
      img: "http://dn-img-page.kakao.com/download/resource?kid=2XcHF/hzacfyyDaP/AQvywUuQOQ9bmwXoyvCKbK&filename=th2",
      subscriptions: "91.9",
      genre: '로맨스',
      rating: '9.5',
      ageLimit: 'All',
      week: ['완결'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 7,
      title: "아빠가 너무 강함",
      img: "http://dn-img-page.kakao.com/download/resource?kid=P06x9/hzacbXZru0/w5BMgYBYL4pp9Rj1c4jaF0&filename=th2",
      subscriptions: "48.5",
      genre: '로판',
      rating: '8.8',
      ageLimit: 'All',
      week: ['수', '목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 8,
      title: "1레벨 플레이어",
      img: "http://dn-img-page.kakao.com/download/resource?kid=6iJrN/hzmU1aifCt/9kruzeXja6oBtgyFLycHK1&filename=th2",
      subscriptions: "19.6",
      genre: '로판',
      rating: '9.1',
      ageLimit: '15',
      week: ['금', '토'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 9,
      title: "어딜 봐요 매니저님",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cqZA0V/hzacd84mNX/s3PtIZmocIWK7ABeG0ac31&filename=th2",
      subscriptions: "18.4",
      genre: '액션무협',
      rating: '9.2',
      ageLimit: 'All',
      week: ['화', '일'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 10,
      title: "경계인",
      img: "http://dn-img-page.kakao.com/download/resource?kid=c3xG5E/hzhOohQOpW/KoaGkWzM6mK9TPOIb2wbE0&filename=th2",
      subscriptions: "9.4",
      genre: '액션무협',
      rating: '9.3',
      ageLimit: '15',
      week: ['목', '토'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 11,
      title: "백작가의 망나니가 되었다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cbjtkI/hzacgYFTkq/PSAiujZt9kOXMOPj1XT7LK&filename=th2",
      subscriptions: "131",
      genre: '액션무협',
      rating: '7.2',
      ageLimit: 'All',
      week: ['월', '수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 12,
      title: "정령왕의 딸",
      img: "http://dn-img-page.kakao.com/download/resource?kid=22qoX/hyCvmRQDSL/5JDKyDHkJgBOI69lg4qdJ1&filename=th2",
      subscriptions: "75",
      genre: 'BL',
      rating: '6.6',
      ageLimit: 'All',
      week: ['목', '금'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 13,
      title: "옷소매 붉은 끝동",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bdXfpL/hzb7sQkGfQ/NT4fYxdUKZWbW7v9Sj4D81&filename=th2",
      subscriptions: "58.4",
      genre: 'BL',
      rating: '7.2',
      ageLimit: '15',
      week: ['수', '목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 14,
      title: "미필적 고의에 의한 관계",
      img: "http://dn-img-page.kakao.com/download/resource?kid=b60gs5/hyQ9S2BUwT/Vv2RtbZab85B2G8UKpaxX0&filename=th2",
      subscriptions: "35.2",
      genre: '소년',
      rating: '8.5',
      ageLimit: 'All',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 15,
      title: "내일의 으뜸",
      img: "http://dn-img-page.kakao.com/download/resource?kid=coktW/hzb7AOnehU/IcN3VcXjLBdbTpRPv8sqQK&filename=th2",
      subscriptions: "23.4",
      genre: '소년',
      rating: '7.4',
      ageLimit: 'All',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 16,
      title: "오라버니가 너무 순해서 걱정이다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=9AhFq/hzb7v7qYBA/VfbltpT4NcWVRRvBSo7ySK&filename=th2",
      subscriptions: "54.1",
      genre: '드라마',
      rating: '8.1',
      ageLimit: 'All',
      week: ['완결'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 17,
      title: "왜 이러세요, 공작님!",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bpui9e/hyVkMY297U/x6PEfl4IECW7Fi2AkBXL31&filename=th2",
      subscriptions: "131.7",
      genre: '로맨스',
      rating: '6.5',
      ageLimit: '15',
      week: ['화'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 18,
      title: "2회차는 레드카펫으로",
      img: "http://dn-img-page.kakao.com/download/resource?kid=jiR4L/hzb7s4AGjp/rSkNu0yVQGFTB3vcnA7Yd1&filename=th2",
      subscriptions: "35.5",
      genre: '드라마',
      rating: '9.1',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 19,
      title: "흑막을 버리는 데 실패했다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=liDhp/hzp2mPH4pp/avQh3sIi2DG85rCRUegvG0&filename=th2",
      subscriptions: "29.9",
      genre: '로맨스',
      rating: '9.6',
      ageLimit: '15',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 20,
      title: "절대무신",
      img: "http://dn-img-page.kakao.com/download/resource?kid=d7xIJb/hy41GOLe3P/buSZKwUMyLBtvX0KxkWSik&filename=th2",
      subscriptions: "61.1",
      genre: '액션무협',
      rating: '10.0',
      ageLimit: 'All',
      week: ['토'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 21,
      title: "비뢰도",
      img: "http://dn-img-page.kakao.com/download/resource?kid=cyq0ma/hzb7yDg2ke/bIzebxQnLC3RJj7mkrwcUK&filename=th2",
      subscriptions: "104.1",
      genre: '액션무협',
      rating: '9.5',
      ageLimit: 'All',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 22,
      title: "호위무사",
      img: "http://dn-img-page.kakao.com/download/resource?kid=O2gvI/hy41MPonM0/exDflmPQEKmkXbFHoWjRsk&filename=th2",
      subscriptions: "23.5",
      genre: '액션무협',
      rating: '8.4',
      ageLimit: '15',
      week: ['금'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 23,
      title: "마검왕",
      img: "http://dn-img-page.kakao.com/download/resource?kid=L1YaG/hyCvfFupwI/RKKFw4IwDhfsppjUQooOY1&filename=th2",
      subscriptions: "229.8",
      genre: '로판',
      rating: '9.2',
      ageLimit: 'All',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 24,
      title: "나쁜 색기 [개정판]",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bhEjzw/hzhOfkJ4Le/Qk9yTzliowfFfy7i3lSYfK&filename=th2",
      subscriptions: "6.8",
      genre: 'BL',
      rating: '9.9',
      ageLimit: 'All',
      week: ['토'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 25,
      title: "우연한 친구",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bWRnqq/hy41LwsibS/tFl0ThHhYEwCWrTjyk2U2k&filename=th2",
      subscriptions: "8.9",
      genre: '드라마',
      rating: '10.0',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 26,
      title: "비선실세 레이디",
      img: "http://dn-img-page.kakao.com/download/resource?kid=JSFp0/hzhOek32wE/p5mq0enZgZ8cgPrEHFit5k&filename=th2",
      subscriptions: "8.9",
      genre: '드라마',
      rating: '9.0',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "김유하",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 27,
      title: "이계 검왕 생존기",
      img: "http://dn-img-page.kakao.com/download/resource?kid=BMO62/hy41I0Dsag/kamDTkurP02yHHrzcZG2S0&filename=th2",
      subscriptions: "8.9",
      genre: '드라마',
      rating: '8.5',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "권순규,스튜디오 크힛,임경배",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 28,
      title: "아 하세요, 금수저 들어갑니다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=lerKD/hyZ8tgaoFo/lqMwFKStxEtUCXNQLitEaK&filename=th2",
      subscriptions: "8.1",
      genre: '드라마',
      rating: '8.5',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "신유성,포르토피노",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 29,
      title: "폭군의 보호자는 악역 마녀입니다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=bOh4De/hy41MhgW8I/UWsfQmQX6Ril8JxTxMXbw0&filename=th2",
      subscriptions: "7.2",
      genre: '드라마',
      rating: '8.5',
      ageLimit: 'All',
      week: ['수'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "만달,하리,라타,블루라군",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
    {
      _id: 30,
      title: "해골병사는 던전을 지키지 못했다",
      img: "http://dn-img-page.kakao.com/download/resource?kid=b7MEYH/hyZ8tNwRHb/pCS6ElNU0zioYLDFfjZkR1&filename=th2",
      subscriptions: "5.2",
      genre: '드라마',
      rating: '6.2',
      ageLimit: 'All',
      week: ['목'],
      description: "여우와 얽힌 친구를 구하라!",
      author: "만달,하리,라타,블루라군",
      status:
        "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
    },
  ];

export const carouselData = [
  {
    _id: 1,
    menu: "웹툰1",
    title: "아빠가 너무 강함",
    subscriptions: 48.5,
    status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
  },
  {
    _id: 2,
    menu: "웹툰2",
    title: "악녀는 마리오네트",
    subscriptions: 15.8,
    status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
  },
  {
    _id: 3,
    menu: "웹툰3",
    title: "도굴왕",
    subscriptions: 209.4,
    status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
  },  {
    _id: 4,
    menu: "웹툰4",
    title: "킹덤",
    subscriptions: 36.1,
    status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
  },  {
    _id: 5,
    menu: "웹툰5",
    title: "귀한용사의 골목식당",
    subscriptions: 23.4,
    status: "https://static-page.kakao.com/static/common/icon_up.svg?51cfaf512283ca0e1eaca53414e35a3f",
  }
]